name: Python application test with Github actions
on:
  push:
    branches: [ "azure" ]
#   pull_request:
#     branches: [ "azure" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.5.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.5.10
      - name: Install dependencies
        run: |
          make install-azure
      - name: Lint with Pylint
        run: |
          make lint
      - name: Test with Pytest
        run: |
          make test
      - name: Format code with Python black
        run: |
          make format
